# Generated by Django 5.0 on 2023-12-27 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='iscompleted',
            new_name='task_complete',
        ),
    ]
