# Generated by Django 5.0 on 2023-12-27 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_rename_iscompleted_task_task_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_complete',
        ),
        migrations.AddField(
            model_name='task',
            name='taskstatus',
            field=models.CharField(choices=[('complete', 'complete'), ('active', 'active')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
