# Generated by Django 5.0 on 2023-12-27 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_task_taskstatus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskImages',
            new_name='TaskImage',
        ),
    ]
