# Generated by Django 5.0 on 2023-12-27 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_rename_taskimages_taskimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskimage',
            name='image',
            field=models.ImageField(default=1, upload_to='media/taskimages'),
            preserve_default=False,
        ),
    ]
