# Generated by Django 5.0 on 2023-12-27 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_taskimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='taskstatus',
        ),
        migrations.AddField(
            model_name='task',
            name='activetask',
            field=models.BooleanField(default=1, verbose_name=True),
            preserve_default=False,
        ),
    ]
