# Generated by Django 5.0 on 2023-12-27 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_remove_task_taskstatus_task_activetask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='activetask',
            field=models.BooleanField(default=True),
        ),
    ]
