# Generated by Django 5.0 on 2023-12-27 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_alter_task_activetask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='activetask',
        ),
        migrations.AddField(
            model_name='task',
            name='task_complete',
            field=models.BooleanField(default=False),
        ),
    ]
